ADFHOST2302="http://csdnim.qtmojo.com";
ADFCID2302=63;
ADFBID2302=2302;
ADFLOC='CNHBWH00';
ADFUSER2302="http://csdnim.qtmojo.com/c?d=csdnim&i=z63,10456520,2302,11569&rf=&a=dICsdsd1o21wp2A5yG97x2LdNVYO&u=";
ALLYESID4="CdZTT1OZG2A5yHY059Q";
ADFPGC="2,8,63,0,3014,2302,11569,10456520";

document.write("<script type='text/javascript'>\n");
document.write("var googletag = googletag || {};\n");
document.write("googletag.cmd = googletag.cmd || [];\n");
document.write("(function() {\n");
document.write("var gads = document.createElement('script');\n");
document.write("gads.async = true;\n");
document.write("gads.type = 'text/javascript';\n");
document.write("var useSSL = 'https:' == document.location.protocol;\n");
document.write("gads.src = (useSSL ? 'https:' : 'http:') + \n");
document.write("'//www.googletagservices.com/tag/js/gpt.js';\n");
document.write("var node = document.getElementsByTagName('script')[0];\n");
document.write("node.parentNode.insertBefore(gads, node);\n");
document.write("})();\n");
document.write("</Scr"+"ipt>\n");
document.write("\n");
document.write("<div id='div-gpt-ad-1430968810821-0'>\n");
document.write("<script type='text/javascript'>\n");
document.write("googletag.cmd.push(function() {\n");
document.write("googletag.defineSlot('/8456/IDG.CN_B2B_csdn.net', [728, 90], 'div-gpt-ad-1430968810821-0')\n");
document.write(".addService(googletag.pubads())\n");
document.write(".setTargeting(\"category\",\"bbs\");\n");
document.write("if (self != top) {\n");
document.write("         googletag.pubads().set(\"page_url\", document.referrer);\n");
document.write("         }\n");
document.write("googletag.enableServices();\n");
document.write("googletag.display('div-gpt-ad-1430968810821-0');\n");
document.write("});\n");
document.write("</Scr"+"ipt>\n");
document.write("</div>");

