ADFHOST3454="http://csdnim.qtmojo.com";
ADFCID3454=166;
ADFBID3454=3454;
ADFLOC='CNHBWH00';
ADFUSER3454="http://csdnim.qtmojo.com/c?d=csdnim&i=z166,10456122,3454,17612&rf=&a=dMCcdgd1o2Lh02A5yG83LX4by79v&u=";
ALLYESID4="CdZTT1OZG2A5yHY059Q";
ADFPGC="2,8,166,0,4552,3454,17612,10456122";

document.write("<script type='text/javascript'>\n");
document.write("var googletag = googletag || {};\n");
document.write("googletag.cmd = googletag.cmd || [];\n");
document.write("(function() {\n");
document.write("var gads = document.createElement('script');\n");
document.write("gads.async = true;\n");
document.write("gads.type = 'text/javascript';\n");
document.write("var useSSL = 'https:' == document.location.protocol;\n");
document.write("gads.src = (useSSL ? 'https:' : 'http:') + \n");
document.write("'//www.googletagservices.com/tag/js/gpt.js';\n");
document.write("var node = document.getElementsByTagName('script')[0];\n");
document.write("node.parentNode.insertBefore(gads, node);\n");
document.write("})();\n");
document.write("</Scr"+"ipt>\n");
document.write("\n");
document.write("<div id='div-gpt-ad-1432179635872-0'>\n");
document.write("<script type='text/javascript'>\n");
document.write("googletag.cmd.push(function() {\n");
document.write("googletag.defineSlot('/8456/IDG.CN_B2B_csdn.net', [160, 600], 'div-gpt-ad-1432179635872-0').addService(googletag.pubads()).setTargeting(\"pos\",\"left\");\n");
document.write("googletag.pubads().enableSingleRequest();\n");
document.write("googletag.enableServices();\n");
document.write("googletag.display('div-gpt-ad-1432179635872-0');\n");
document.write("});\n");
document.write("</Scr"+"ipt>\n");
document.write("</div>");

