ADFHOST2818="http://csdnim.qtmojo.com";
ADFCID2818=167;
ADFBID2818=2818;
ADFLOC='CNHBWH00';
ADFUSER2818="http://csdnim.qtmojo.com/c?d=csdnim&i=z167,10457869,2818,14259&rf=&a=dZC5dgd1o2N6c2A5yG63cphdaNK7&u=";
ALLYESID4="CdZTT1OZG2A5yHY059Q";
ADFPGC="2,8,167,0,3712,2818,14259,10457869";

document.write("<script type='text/javascript'>\n");
document.write("var googletag = googletag || {};\n");
document.write("googletag.cmd = googletag.cmd || [];\n");
document.write("(function() {\n");
document.write("var gads = document.createElement('script');\n");
document.write("gads.async = true;\n");
document.write("gads.type = 'text/javascript';\n");
document.write("var useSSL = 'https:' == document.location.protocol;\n");
document.write("gads.src = (useSSL ? 'https:' : 'http:') + \n");
document.write("'//www.googletagservices.com/tag/js/gpt.js';\n");
document.write("var node = document.getElementsByTagName('script')[0];\n");
document.write("node.parentNode.insertBefore(gads, node);\n");
document.write("})();\n");
document.write("</Scr"+"ipt>\n");
document.write("\n");
document.write("<div id='div-gpt-ad-1432179799713-0'>\n");
document.write("<script type='text/javascript'>\n");
document.write("googletag.cmd.push(function() {\n");
document.write("googletag.defineSlot('/8456/IDG.CN_B2B_csdn.net', [160, 600], 'div-gpt-ad-1432179799713-0').addService(googletag.pubads()).setTargeting(\"pos\",\"right\");\n");
document.write("googletag.pubads().enableSingleRequest();\n");
document.write("if (self != top) {\n");
document.write("         googletag.pubads().set(\"page_url\", document.referrer);\n");
document.write("         }\n");
document.write("googletag.enableServices();\n");
document.write("googletag.display('div-gpt-ad-1432179799713-0');\n");
document.write("});\n");
document.write("</Scr"+"ipt>\n");
document.write("</div>");

